In [1]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from pymongo import MongoClient, ASCENDING
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

In [2]:
MONGO_URI = 'mongodb+srv://25092413_db_user:rZTgL0uPvIArdFen@cluster0.vffsegw.mongodb.net/?appName=Cluster0'
DB_NAME   = 'ProjectGroup3'
client = MongoClient(MONGO_URI)
db     = client[DB_NAME]
collection = db['Group3']

In [3]:
print(f'Connected to MongoDB — database: {DB_NAME}')
print('Existing collections:', db.list_collection_names())

wind_doc = collection.find_one({"wind_farms": {"$exists": True}})
wind_data = wind_doc['wind_farms']

df_wind = pd.DataFrame.from_dict(wind_data, orient='index')
df_wind.reset_index(inplace=True)
df_wind.rename(columns={'index': 'wind_farm_name'}, inplace=True)
df_wind['lat'] = df_wind['location'].apply(lambda x: x['lat'])
df_wind['lon'] = df_wind['location'].apply(lambda x: x['lon'])
df_wind.drop(columns=['location'], inplace=True)
display(df_wind)

Connected to MongoDB — database: ProjectGroup3
Existing collections: ['Group3']

,wind_farm_name,id,installed_capacity_mw,commissioned,turbine_type,platform_height,wind_height_scaling_factor,lat,lon
0,Borssele_12,1,752.0,20/05/2020,SG 8.0-167 DD,116.5,,51.75,3.25
1,Borssele_34,2,731.5,28/01/2021,V164-9.5,100.0,,51.72,3.22
2,Gemini,3,600.0,08/05/2017,SWT-4.0-130,120.0,,54.03,5.95
3,Hollandse_Kust_Zuid,4,1420.0,23/08/2022,SG 11.0-200 DD,125.5,,52.35,4.25
4,Hollandse_Kust_Noord,5,760.0,31/01/2023,SG 11.0-200 DD,125.5,,52.75,4.50

In [4]:
entso_doc = collection.find_one({
    "ENTSO_Installed_offshore": {"$exists": True}
})

entso_data = entso_doc['ENTSO_Installed_offshore']

df_ENTSO = pd.DataFrame(entso_data)
df_ENTSO.dropna(axis=1, how='all', inplace=True)

display(df_ENTSO)

,year,total_installed_capacity_MW,Borssele_34,Hollandse_Kust_Zuid,Hollandse_Kust_Noord,Gemini,Borssele_12,Others
0,2015,228,0.0,0,0,0,0,108
1,2016,957,0.0,0,0,0,0,252
2,2017,957,0.0,0,0,0,0,252
3,2018,957,0.0,0,0,600,0,252
4,2019,957,0.0,0,0,600,0,252
5,2020,2460,0.0,0,0,600,0,252
6,2021,2460,0.0,0,0,600,752,252
7,2022,2460,731.5,0,0,600,752,501
8,2023,4739,731.5,1420,0,600,752,501
9,2024,4739,731.5,1420,760,600,752,501
10,2025,4739,731.5,1420,760,600,752,501
11,2026,4739,731.5,1420,760,600,752,501